name: Generate and Upload Documentation

stages:
  - build
  - deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  generate_and_upload_docs:
    runs-on: ubuntu-latest
    stage: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 # Adjust the Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python3/requirements.txt

      - name: Generate Documentation
        run: |
          pdoc -o docs python3/src  # Adjust the input and output directories as needed

      - name: Archive Directory
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs

  create_github_pages:
      runs-on: ubuntu-latest
      stage: deploy

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: docs
            path: ./python3/github_pages/docs
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: python3/github_pages
